[package]
name = "AntiAFK-RBX-Sober"
version = "0.2.0"
edition = "2024"
description = "AntiAFK application for Sober (Roblox for Linux) on Linux"
repository = "https://github.com/Agzes/AntiAFK-RBX-Sober"
license = "MIT"
keywords = ["roblox", "linux", "antiafk", "sober", "hyprland"]

[dependencies]
gtk = { version = "0.7", package = "gtk4", features = ["v4_10"] }
glib = "0.18"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
evdev = "0.13.2"
ksni = { version = "0.3.6", features = ["blocking"] }
clap = { version = "4.6.7", features = ["derive"] }
image = "0.25.10"
notify-rust = "4.18.0"
dirs = "7.0.0"

[package.metadata.appimage]
name = "AntiAFK-RBX-Sober"
icon = "assets/logo.png"
desktop_entry = "dev.agzes.antiafk-rbx-sober.desktop"
auto_link = true
category = "Utility"