[package]
name = "AntiAFK-RBX-Sober"
version = "1.0.0"
edition = "2024"
description = "AntiAFK application for Sober (Roblox for Linux) on Linux"
repository = "https://github.com/Agzes/AntiAFK-RBX-Sober"
license = "MIT"
keywords = ["roblox", "linux", "antiafk", "sober", "hyprland"]

[dependencies]
iced = { version = "0.14", default-features = false, features = [
    "wgpu",
    "tiny-skia",
    "wayland",
    "x11",
    "tokio",
    "image",
    "svg",
    "advanced",
    "web-colors",
    "crisp",
    "linux-theme-detection",
] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
evdev = "0.13.2"
ksni = { version = "0.3.6", features = ["blocking"] }
clap = { version = "4.6.7", features = ["derive"] }
image = "0.25.10"
notify-rust = "4.18.1"
dirs = "7.0.0"
cosmic-client-toolkit = "0.2.0"
libc = "0.2"

[package.metadata.appimage]
name = "AntiAFK-RBX-Sober"
icon = "assets/logo.png"
desktop_entry = "dev.agzes.antiafk-rbx-sober.desktop"
auto_link = true
category = "Utility"

[package.metadata.deb]
name = "antiafk-rbx-sober"
maintainer = "agzes <agzes0@proton.me>"
copyright = "2026, agzes"
license-file = ["LICENSE"]
extended-description = "Native Linux Anti-AFK utility for Sober (Roblox)"
depends = "$auto"
section = "utils"
priority = "optional"
assets = [
    ["target/release/AntiAFK-RBX-Sober", "usr/bin/AntiAFK-RBX-Sober", "755"],
    ["dev.agzes.antiafk-rbx-sober.desktop", "usr/share/applications/dev.agzes.antiafk-rbx-sober.desktop", "644"],
    ["assets/logo.png", "usr/share/icons/hicolor/128x128/apps/dev.agzes.antiafk-rbx-sober.png", "644"],
    ["assets/logo.png", "usr/share/pixmaps/dev.agzes.antiafk-rbx-sober.png", "644"],
]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/AntiAFK-RBX-Sober", dest = "/usr/bin/AntiAFK-RBX-Sober", mode = "755" },
    { source = "dev.agzes.antiafk-rbx-sober.desktop", dest = "/usr/share/applications/dev.agzes.antiafk-rbx-sober.desktop", mode = "644" },
    { source = "assets/logo.png", dest = "/usr/share/icons/hicolor/128x128/apps/dev.agzes.antiafk-rbx-sober.png", mode = "644" },
    { source = "assets/logo.png", dest = "/usr/share/pixmaps/dev.agzes.antiafk-rbx-sober.png", mode = "644" },
]
