[package]
name = "AntiAFK-RBX-Sober"
version = "1.0.0"
edition = "2024"
description = "AntiAFK application for Sober (Roblox for Linux) on Linux"
repository = "https://github.com/Agzes/AntiAFK-RBX-Sober"
license = "MIT"
keywords = ["roblox", "linux", "antiafk", "sober", "hyprland"]

[dependencies]
iced = { version = "0.14", default-features = false, features = [
    "wgpu",
    "tiny-skia",
    "wayland",
    "x11",
    "tokio",
    "image",
    "svg",
    "advanced",
    "web-colors",
    "crisp",
    "linux-theme-detection",
] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
evdev = "0.13.2"
ksni = { version = "0.3.6", features = ["blocking"] }
clap = { version = "4.6.7", features = ["derive"] }
image = "0.25.10"
notify-rust = "4.18.1"
dirs = "7.0.0"
cosmic-client-toolkit = "0.2.0"
libc = "0.2"

[package.metadata.appimage]
name = "AntiAFK-RBX-Sober"
icon = "assets/logo.png"
desktop_entry = "dev.agzes.antiafk-rbx-sober.desktop"
auto_link = true
category = "Utility"
